# Generated by Django 4.2.1 on 2023-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_flora_userselection_delete_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flora',
            name='harvest_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flora',
            name='harvest_start',
            field=models.DateField(),
        ),
    ]
