# Generated by Django 4.2.2 on 2023-06-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_flora_harvest_end_alter_flora_harvest_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='flora',
            name='plant_category',
            field=models.CharField(choices=[('tee', 'tee'), ('seen', 'seen'), ('mari', 'mari'), ('meditsiiniline', 'meditsiiniline')], default='tee', max_length=50),
            preserve_default=False,
        ),
    ]
