# Generated by Django 4.2.2 on 2023-06-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_flora_plant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flora',
            name='plant_category',
            field=models.CharField(choices=[('tee', 'tee'), ('salat', 'salat'), ('seen', 'seen'), ('mari', 'mari'), ('meditsiiniline', 'meditsiiniline')], max_length=50),
        ),
    ]
