# Generated by Django 4.2.2 on 2023-06-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_flora_plant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flora',
            name='harvest_end',
        ),
        migrations.RemoveField(
            model_name='flora',
            name='harvest_start',
        ),
        migrations.AddField(
            model_name='flora',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='flora',
            name='harvest_end_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flora',
            name='harvest_end_week',
            field=models.IntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flora',
            name='harvest_start_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flora',
            name='harvest_start_week',
            field=models.IntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flora',
            name='picture_url',
            field=models.URLField(null=True),
        ),
    ]
