# Generated by Django 4.2.2 on 2023-06-21 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_remove_flora_harvest_end_remove_flora_harvest_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flora',
            name='harvest_end_week',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='flora',
            name='harvest_start_week',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='flora',
            name='plant_category',
            field=models.CharField(choices=[('taim', 'taim'), ('seen', 'seen'), ('mari', 'mari'), ('muu', 'muu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='selected_plants',
            field=models.ManyToManyField(null=True, to='website.flora'),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
