# Generated by Django 4.2.2 on 2023-07-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_flora_harvest_end_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flora',
            name='plant_category',
            field=models.CharField(choices=[('Plants', 'Plants'), ('Mushrooms', 'Mushrooms'), ('Berries', 'Berries'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='selected_plants',
            field=models.ManyToManyField(to='website.flora'),
        ),
    ]
